apiVersion: v1
kind: ServiceAccount
metadata:
  name: topsis-scheduler
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: topsis-scheduler
rules:
- apiGroups: [""]
  resources: ["pods", "nodes"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods/binding"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: topsis-scheduler
subjects:
- kind: ServiceAccount
  name: topsis-scheduler
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: topsis-scheduler
  apiGroup: rbac.authorization.k8s.io