apiVersion: v1
kind: Namespace
metadata:
  name: scheduler-test
  labels:
    purpose: testing
    scheduler: enhanced-scheduler

---
apiVersion: v1
kind: Namespace
metadata:
  name: scheduler-monitoring
  labels:
    purpose: monitoring
    scheduler: enhanced-scheduler