apiVersion: v1
kind: ServiceAccount
metadata:
  name: metrics-agent-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metrics-agent-role
rules:
- apiGroups: [""]
  resources: ["pods", "nodes"]
  verbs: ["get", "watch", "list"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: metrics-agent-role-binding
subjects:
- kind: ServiceAccount
  name: metrics-agent-sa
  namespace: default
roleRef:
  kind: ClusterRole
  name: metrics-agent-role
  apiGroup: rbac.authorization.k8s.io