apiVersion: apps/v1
kind: Deployment
metadata:
  name: process-image
spec:
  replicas: 1
  selector:
    matchLabels:
      app: process-image
  template:
    metadata:
      labels:
        app: process-image
    spec:
      schedulerName: topsis-scheduler
      containers:
        - name: process-image
          image: ppreejit/process-image:v2
          imagePullPolicy: Always
