apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: topsis-scheduler-role
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["pods", "events"]
    verbs: ["get", "list", "watch", "create", "patch", "update"]
  - apiGroups: [""]
    resources: ["pods/binding"]
    verbs: ["create"]
