apiVersion: v1
kind: Service
metadata:
  name: kube-scheduler-metrics
  namespace: kube-system
  labels:
    component: kube-scheduler
spec:
  ports:
  - name: https-metrics
    port: 10259
    targetPort: 10259
    protocol: TCP
  selector:
    component: kube-scheduler