apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: topsis-scheduler-binding
subjects:
- kind: ServiceAccount
  name: topsis-scheduler-sa
  namespace: default  # Change this if the scheduler is in a different namespace
roleRef:
  kind: ClusterRole
  name: topsis-scheduler-role
  apiGroup: rbac.authorization.k8s.io
