apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: topsis-scheduler-rolebinding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: topsis-scheduler-sa
    namespace: default
roleRef:
  kind: Role
  name: topsis-scheduler-role
  apiGroup: rbac.authorization.k8s.io
