apiVersion: v1
kind: Service
metadata:
  name: linear-regression-service
spec:
  selector:
    app: linear-regression
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: process-image-service
spec:
  selector:
    app: process-image
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
