apiVersion: v1
kind: ServiceAccount
metadata:
  name: topsis-scheduler
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: topsis-scheduler
rules:
- apiGroups: [""]
  resources: ["pods", "nodes", "events"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]
- apiGroups: [""]
  resources: ["pods/binding"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: topsis-scheduler
subjects:
- kind: ServiceAccount
  name: topsis-scheduler
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: topsis-scheduler
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: topsis-scheduler
  namespace: kube-system
  labels:
    app: topsis-scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: topsis-scheduler
  template:
    metadata:
      labels:
        app: topsis-scheduler
    spec:
      serviceAccountName: topsis-scheduler
      schedulerName: topsis-scheduler
      containers:
      - name: topsis-scheduler
        image: ppreejit/topsis-scheduler:v16
        imagePullPolicy: IfNotPresent
        env:
        - name: JAVA_TOOL_OPTIONS
          value: "-Djava.util.logging.config.file=/app/logging.properties"